import type { Metadata } from 'next'
import NavBar from '@/components/landing/NavBar'
import Footer from '@/components/landing/Footer'
import { getDictionary } from '@/lib/i18n'
import { researchGuides } from '@/lib/research-guides'
import { glossaryTerms } from '@/lib/glossary'
import { brandProfile, getSiteUrl } from '@/lib/seo'

export const metadata: Metadata = { title: 'E-Ticaret Dönüşüm Optimizasyonu Rehberi', description: 'Ürün sayfası, sepet, checkout, teslimat ve iade deneyimini dönüşümden önce katkı payıyla birlikte optimize edin.', alternates: { canonical: '/rehberler/donusum-optimizasyonu' } }
const termSlugs = ['donusum-orani', 'ortalama-sepet-tutari', 'iade-orani', 'katki-payi']
const toolCards = [
  { title: 'E-Ticaret Strateji ve Pazarlama Analizi', description: 'Sepet, dönüşüm ve ürün ekonomisini aynı senaryo üzerinde karşılaştırın.', href: '/araclar/e-ticaret-strateji-pazarlama-analizi' },
  { title: 'Kâr Marjı Hesaplayıcı', description: 'Dönüşüm artışının gerçekten katkı üretip üretmediğini sipariş ekonomisiyle kontrol edin.', href: '/araclar/kar-marji-hesaplayici' },
]

export default function ConversionPillarPage() {
  const t = getDictionary('tr'); const siteUrl = getSiteUrl()
  const guide = researchGuides.find((item) => item.slug === 'teslimat-iade-donusum-kontrol-listesi')
  const clusterTerms = termSlugs.map((slug) => glossaryTerms.find((term) => term.slug === slug)).filter(Boolean)
  const jsonLd = { '@context': 'https://schema.org', '@type': 'CollectionPage', name: 'E-Ticaret Dönüşüm Optimizasyonu Rehberi', description: metadata.description, url: `${siteUrl}/rehberler/donusum-optimizasyonu`, inLanguage: 'tr-TR', author: { '@type': 'Person', name: brandProfile.name, url: siteUrl }, hasPart: guide ? [{ '@type': 'Article', name: guide.title, url: `${siteUrl}/rehberler/${guide.slug}` }] : [] }
  return <main className="page"><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} /><NavBar t={t} />
    <section className="hero-shell conversion-pillar-hero"><div className="wrap hero"><div className="hero-copy"><div className="crumb"><i aria-hidden="true" /> DÖNÜŞÜM OPTİMİZASYONU / ANA ÖĞRENME YOLU</div><h1>Daha çok sipariş değil, <span className="accent">daha iyi sepet</span> kurun.</h1><p className="intro">Ürün sayfasından checkout’a kadar güven, hız, teslimat ve iade sinyallerini dönüşüm ve katkı payıyla birlikte ölçün.</p><div className="actions-row"><a className="btn hero-primary" href="#ogrenme-yolu">Denetim yoluna başla ↘</a><a className="hero-link" href="/araclar/e-ticaret-strateji-pazarlama-analizi">Senaryo çalıştır</a></div><div className="signals"><span className="tag"><i />1 uygulama rehberi</span><span className="tag"><i />2 çalışan analiz aracı</span><span className="tag"><i />Katkı odaklı test</span></div></div><div className="conversion-console" aria-label="Dönüşüm karar akışı"><div className="conversion-console-head"><span className="eyebrow">CHECKOUT KONSOLU</span><i>TEST → KATKI</i></div><div className="conversion-console-flow"><div><small>01 / GÜVEN</small><strong>Ürün sayfası</strong><p>Vaat, fiyat ve kanıt net mi?</p></div><div><small>02 / SÜRTÜNME</small><strong>Sepet</strong><p>Ücret ve eşik geç mi görünüyor?</p></div><div><small>03 / TESLİMAT</small><strong>Checkout</strong><p>Tarih, seçenek ve iade açık mı?</p></div><div><small>04 / EKONOMİ</small><strong>Katkı</strong><p>Artan sipariş toplam katkıyı büyütüyor mu?</p></div></div></div></div></section>
    <section className="section-band band-dark conversion-principle"><div className="wrap section"><span className="eyebrow">60 SANİYELİK ÇERÇEVE</span><h2>Dönüşüm oranı teşhistir; ekonomik sonuç karardır.</h2><p>Bir test sipariş oranını artırabilirken indirim, kargo veya iade maliyetini de büyütebilir. Hipotezi önce kullanıcı sürtünmesiyle, sonra sipariş başına katkı ve toplam katkıyla doğrulayın.</p></div></section>
    <section id="ogrenme-yolu" className="section-band band-paper"><div className="wrap section"><div className="head"><div><span className="eyebrow">ADIM ADIM / 1 REHBER</span><h2>Dönüşüm denetim yolu.</h2></div><p>Ücretsiz kargo ve iade kararlarını yalnız CVR ile değil, teslimat sonrası katkıyla test edin.</p></div><div className="profitability-path conversion-path">{guide && <a href={`/rehberler/${guide.slug}`}><span>01</span><div><small>{guide.category} · {guide.readingTime} DK</small><h3>{guide.title}</h3><p>{guide.excerpt}</p></div><i>Rehberi aç →</i></a>}</div></div></section>
    <section className="section-band band-cyan"><div className="wrap section"><div className="head"><div><span className="eyebrow">HESAPLAMA KATMANI</span><h2>Testi katkıyla birlikte çalıştırın.</h2></div><p>Sepet, fiyat, kargo ve iade varsayımlarını aynı senaryoda görün.</p></div><div className="grid profitability-tools">{toolCards.map((tool, index) => <a key={tool.href} className="card" href={tool.href}><span className="eyebrow">0{index + 1} · ÜCRETSİZ ARAÇ</span><h3>{tool.title}</h3><p>{tool.description}</p><span className="link">Aracı aç</span></a>)}</div></div></section>
    <section className="section-band band-surface"><div className="wrap section"><div className="head"><div><span className="eyebrow">KAVRAM HARİTASI</span><h2>Aynı dönüşüm dilini kurun.</h2></div><p>CVR, sepet, iade ve katkıyı aynı tanım ve dönemle izleyin.</p></div><div className="pillar-term-grid">{clusterTerms.map((term) => term && <a key={term.slug} href={`/sozluk/${term.slug}`}><span>{term.english}</span><strong>{term.term}</strong><i>Tanımı aç →</i></a>)}</div><a className="btn alt pillar-all-terms" href="/sozluk">Tüm kavramları gör →</a></div></section><Footer t={t} /></main>
}
