import type { Metadata } from 'next'
import NavBar from '@/components/landing/NavBar'
import Footer from '@/components/landing/Footer'
import { getDictionary } from '@/lib/i18n'
import { guides } from '@/lib/guides'
import { glossaryTerms } from '@/lib/glossary'
import { brandProfile, getSiteUrl } from '@/lib/seo'

export const metadata: Metadata = { title: 'E-Ticaret Raporlama ve Dashboard Rehberi', description: 'KPI seçimi, veri sözlüğü, event takibi ve haftalık yönetim raporunu tek bir e-ticaret raporlama sisteminde kurun.', alternates: { canonical: '/rehberler/veri-raporlama' } }
const guideSlugs = ['e-ticaret-dashboard-metrikleri', 'haftalik-reklam-raporu-nasil-hazirlanir']
const termSlugs = ['roas', 'mer', 'donusum-orani', 'ortalama-sepet-tutari']
const toolCards = [
  { title: 'E-Ticaret Strateji ve Pazarlama Analizi', description: 'Ürün, reklam, marj ve sabit gider sinyallerini tek yönetim görünümünde analiz edin.', href: '/araclar/e-ticaret-strateji-pazarlama-analizi' },
  { title: 'Türkiye E-Ticaret Kârlılık Nabzı 2026', description: 'Benchmark raporundaki kapsam, varsayım ve sınırlamaları kendi KPI sözlüğünüzle karşılaştırın.', href: '/raporlar/turkiye-e-ticaret-karlilik-nabzi-2026' },
]

export default function ReportingPillarPage() {
  const t = getDictionary('tr'); const siteUrl = getSiteUrl()
  const clusterGuides = guideSlugs.map((slug) => guides.find((guide) => guide.slug === slug)).filter(Boolean)
  const clusterTerms = termSlugs.map((slug) => glossaryTerms.find((term) => term.slug === slug)).filter(Boolean)
  const jsonLd = { '@context': 'https://schema.org', '@type': 'CollectionPage', name: 'E-Ticaret Raporlama ve Dashboard Rehberi', description: metadata.description, url: `${siteUrl}/rehberler/veri-raporlama`, inLanguage: 'tr-TR', author: { '@type': 'Person', name: brandProfile.name, url: siteUrl }, hasPart: clusterGuides.map((guide) => ({ '@type': 'Article', name: guide?.title, url: `${siteUrl}/rehberler/${guide?.slug}` })) }
  return <main className="page"><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} /><NavBar t={t} />
    <section className="hero-shell reporting-pillar-hero"><div className="wrap hero"><div className="hero-copy"><div className="crumb"><i aria-hidden="true" /> VERİ VE RAPORLAMA / ANA ÖĞRENME YOLU</div><h1>Dashboard değil, <span className="accent">karar ritmi</span> kurun.</h1><p className="intro">KPI seçimini, veri tanımlarını ve haftalık raporlama akışını aynı doğruluk kaynağında birleştirerek ekiplerin aynı kararı görmesini sağlayın.</p><div className="actions-row"><a className="btn hero-primary" href="#ogrenme-yolu">Raporlama yoluna başla ↘</a><a className="hero-link" href="/araclar/e-ticaret-strateji-pazarlama-analizi">Analizi aç</a></div><div className="signals"><span className="tag"><i />2 uygulama rehberi</span><span className="tag"><i />1 analiz aracı</span><span className="tag"><i />Tek doğruluk kaynağı</span></div></div><div className="reporting-console" aria-label="Raporlama karar akışı"><div className="reporting-console-head"><span className="eyebrow">YÖNETİM RAPORU</span><i>VERİ TAZELİĞİ / 24 SAAT</i></div><div className="reporting-console-flow"><div><small>01 / TANIM</small><strong>Veri sözlüğü</strong><p>Payda, dönem ve kaynak net.</p></div><div><small>02 / SİNYAL</small><strong>KPI</strong><p>Gelir, katkı, reklam ve müşteri.</p></div><div><small>03 / TEŞHİS</small><strong>Kırılım</strong><p>Kanal, ürün, cihaz ve kohort.</p></div><div><small>04 / KARAR</small><strong>Aksiyon</strong><p>Sahip, tarih ve beklenen etki.</p></div></div></div></div></section>
    <section className="section-band band-dark reporting-principle"><div className="wrap section"><span className="eyebrow">60 SANİYELİK ÇERÇEVE</span><h2>İyi dashboard daha çok grafik değil, daha az belirsizlik üretir.</h2><p>Her KPI’ın formülünü, veri kaynağını, tazeliğini ve sorumlusunu yazın. Raporu yalnız “ne oldu?” diye değil; “neden oldu, ne yapacağız, ne zaman tekrar bakacağız?” diye tasarlayın.</p></div></section>
    <section id="ogrenme-yolu" className="section-band band-paper"><div className="wrap section"><div className="head"><div><span className="eyebrow">ADIM ADIM / {clusterGuides.length} REHBER</span><h2>Raporlama öğrenme yolu.</h2></div><p>Önce metrik sözlüğünü sabitleyin; sonra haftalık ritmi ve karar sahipliğini kurun.</p></div><div className="profitability-path reporting-path">{clusterGuides.map((guide, index) => guide && <a key={guide.slug} href={`/rehberler/${guide.slug}`}><span>{String(index + 1).padStart(2, '0')}</span><div><small>{guide.category} · {guide.readingTime} DK</small><h3>{guide.title}</h3><p>{guide.excerpt}</p></div><i>Rehberi aç →</i></a>)}</div></div></section>
    <section className="section-band band-cyan"><div className="wrap section"><div className="head"><div><span className="eyebrow">UYGULAMA KATMANI</span><h2>Sinyali karara bağlayın.</h2></div><p>Analiz ve benchmark çıktısını haftalık yönetim aksiyonuna dönüştürün.</p></div><div className="grid profitability-tools">{toolCards.map((tool, index) => <a key={tool.href} className="card" href={tool.href}><span className="eyebrow">0{index + 1} · KAYNAK</span><h3>{tool.title}</h3><p>{tool.description}</p><span className="link">Aç →</span></a>)}</div></div></section>
    <section className="section-band band-surface"><div className="wrap section"><div className="head"><div><span className="eyebrow">KAVRAM HARİTASI</span><h2>Ortak metrik dilini kurun.</h2></div><p>Her KPI’ı formül ve kapsamıyla ekip içinde aynı okuyun.</p></div><div className="pillar-term-grid">{clusterTerms.map((term) => term && <a key={term.slug} href={`/sozluk/${term.slug}`}><span>{term.english}</span><strong>{term.term}</strong><i>Tanımı aç →</i></a>)}</div><a className="btn alt pillar-all-terms" href="/sozluk">Tüm kavramları gör →</a></div></section><Footer t={t} /></main>
}
